art/urls.py
from django.conf.urls import url
from art import views
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import settings

urlpatterns = [#patterns(views',
        url(r'^$', views.index, name="index"),
        url(r'^trash/$', views.trash, name="trash"),
        url(r'^stats/$', views.stats, name="stats"),
        url(r'^top/$', views.top, name="top"),
        url(r'^gallery/$', views.gallery, name="gallery"),
        url(r'^location/$', views.location, name="location"),
        url(r'^get_score/$', views.get_score, name="get_score"),
        url(r'^demo/$', views.demo, name="demo"),
        url(r'^save_gallery/$', views.save_gallery, name="save_gallery"),
        url(r'^get_gallery_names/$', views.get_gallery_names, name="get_gallery_names"),
        url(r'^get_artist_status/$', views.get_artist_status, name="get_artist_status"),
        url(r'^get_galleries/$', views.get_galleries, name="get_galleries"),
        url(r'^gallery_get/$', views.gallery_get, name="gallery_get"),
        url(r'^svm/$', views.svm, name="svm"),
        url(r'^svm_add/$', views.svm_add, name="svm_add"),
        url(r'^svm_get_article/$', views.svm_get_article, name="svm_get_article"),
        url(r'^svm_add_article/$', views.svm_add_article, name="svm_add_article"),
        url(r'^svm_test/$', views.svm_test, name="svm_test"),
        url(r'^clean/$', views.clean, name="clean"),
        url(r'^removeLinkArtist/$', views.removeLinkArtist, name="removeLinkArtist"),
        url(r'^restoreLinkArtist/$', views.restoreLinkArtist, name="restoreLinkArtist"),
        url(r'^removeLink/$', views.removeLink, name="removeLink"),
        url(r'^restoreLink/$', views.restoreLink, name="restoreLink"),
        url(r'^getScore/$', views.getScore, name="getScore"),
        url(r'^getDomain/$', views.getDomain, name="getDomain"),
        url(r'^getArtistGallery/$', views.getArtistGallery, name="getArtistGallery"),
        url(r'^getLink/$', views.getLink, name="getLink"),
        url(r'^getTrash/$', views.getTrash, name="getTrash"),
        url(r'^getLatest/$', views.getLatest, name="getLatest"),
        url(r'^getMore/$', views.getMore, name="getMore"),
        url(r'^getArtist/$', views.getArtist, name="getArtist"),
        url(r'^settings/$', views.settings, name="settings"),
        url(r'^add_gallery/$', views.add_gallery, name="add_gallery"),
        url(r'^remove_gallery/$', views.remove_gallery, name="remove_gallery"),
        url(r'^add_artist/$', views.add_artist, name="add_artist"),
        url(r'^add_artist_test/$', views.add_artist_test, name="add_artist_test"),
        url(r'^remove_artist/$', views.remove_artist, name="remove_artist"),
        url(r'^remove_artist_all/$', views.remove_artist_all, name="remove_artist_all"),
        url(r'^remove_artfacts/$', views.remove_artfacts, name="remove_artfacts"),
        url(r'^upload_artist_csv/$', views.upload_artist_csv, name="upload_artist_csv"),
        url(r'^add_article/$', views.add_article, name="add_article"),
        url(r'^get_recent_articles/$', views.get_recent_articles, name="get_recent_articles"),
        url(r'^get_article/$', views.get_article, name="get_article"),
        url(r'^check_article/$', views.check_article, name="check_article"),
        url(r'^get_artist_from_website/$', views.get_artist_from_website, name="get_artist_from_website"),
        url(r'^add_mapping/$', views.add_mapping, name="add_mapping"),
        url(r'^remove_mapping/$', views.remove_mapping, name="remove_mapping"),
        url(r'^search_gallery/$', views.search_gallery, name="search_gallery"),
        url(r'^update_gallery/$', views.update_gallery, name="update_gallery"),
        url(r'^search_artist/$', views.search_artist, name="search_artist"),
        url(r'^search_artist_all/$', views.search_artist_all, name="search_artist_all"),
        url(r'^search_artfacts/$', views.search_artfacts, name="search_artfacts"),
        url(r'^changelog/$', views.changelog, name="changelog"),
        url(r'^search/', views.search, name="search" ),
]

#if settings.DEBUG == True:
        #urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('art.urls', namespace="art", app_name="art")),
    url(r'^art/', include('art.urls', namespace="art", app_name="art")),
    url(r'^music/', include('music.urls', namespace="music", app_name="music")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^art/', include('art.urls')),
]
if settings.DEBUG == True:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

art/views.py
from django.shortcuts import render
from django.http import HttpResponse
from art.models import ArtistScore, RssArtistIndex, RssContent, Toplists
from django.core import serializers
from django.db import connections
from django.views.decorators.csrf import csrf_exempt
import urllib2
import json
import datetime as dt
import logging
import numpy as np
#from optparse import OptionParser
import sys
from time import time
import MySQLdb
from MySQLdb import cursors
import os.path
import itertools
import operator
#from operator import itemgetter
import random
import re
from bs4 import BeautifulSoup
#from bs4 import SoupStrainer
from urlparse import urlparse
from scrapy.selector import HtmlXPathSelector
from urlparse import urljoin
from selenium import webdriver
from time import sleep
#import subprocess
import os
#import string
#from pyvirtualdisplay import Display
import pyvirtualdisplay
#from selenium.webdriver.firefox.webdriver import FirefoxBinary
from googleplaces import GooglePlaces, types
from factual import Factual
from factual.utils import circle
from collections import OrderedDict
from googlesearch import GoogleSearch
import time
from time import mktime
import math
import decimal
from random import randrange
from datetime import timedelta, time, tzinfo, datetime
import time
import tldextract
from lxml.html.clean import Cleaner
from goose import Goose
from readability.readability import Document
from boilerpipe.extract import Extractor
from cookielib import CookieJar
import daily_update as du




from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.feature_extraction.text import HashingVectorizer
#from sklearn.feature_selection import SelectKBest, chi2
#from sklearn.linear_model import RidgeClassifier
#from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
#from sklearn.linear_model import Perceptron
#from sklearn.linear_model import PassiveAggressiveClassifier
#from sklearn.naive_bayes import BernoulliNB, MultinomialNB
#from sklearn.neighbors import KNeighborsClassifier
#from sklearn.neighbors import NearestCentroid
#from sklearn.utils.extmath import density
from sklearn.utils import check_random_state
#from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.externals import joblib

ua = [
            "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6",
            "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:5.0) Gecko/20100101 Firefox/5.0",
            "Mozilla/5.0 (Windows NT 6.1.1; rv:5.0) Gecko/20100101 Firefox/5.0",
            "Mozilla/5.0 (X11; U; Linux i586; de; rv:5.0) Gecko/20100101 Firefox/5.0",
            "Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.1 (KHTML, like Gecko) Ubuntu/11.04 Chromium/14.0.825.0 Chrome/14.0.825.0 Safari/535.1",
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.824.0 Safari/535.1",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:5.0) Gecko/20100101 Firefox/5.0",
            "Mozilla/5.0 (Macintosh; PPC MacOS X; rv:5.0) Gecko/20110615 Firefox/5.0",
            "Mozilla/5.0 (Windows; U; MSIE 9.0; WIndows NT 9.0; en-US))",
            "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/4.0; Media Center PC 4.0; SLCC1; .NET CLR 3.0.04320)",
            "Mozilla/5.0 (Windows; U; MSIE 7.0; Windows NT 6.0; en-US)",
            "Mozilla/5.0 (compatible; Konqueror/4.5; FreeBSD) KHTML/4.5.4 (like Gecko)",
            "Opera/9.80 (Windows NT 6.1; U; es-ES) Presto/2.9.181 Version/12.00",
            "Opera/9.80 (X11; Linux x86_64; U; fr) Presto/2.9.168 Version/11.50",
            "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; de-at) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
            "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_7; da-dk) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
    ]

class DateTimeEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, dt.datetime):
            return int(mktime(obj.timetuple()))

        return json.JSONEncoder.default(self, obj)

class DecimalEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, decimal.Decimal):
            return float(o)

        return super(DecimalEncoder, self).default(o)


def index(request):
    #template = loader.get_template('art/index.html')
    nextoffset = 0
    previousoffset = 0
    try:
        nextoffset = int(request.GET['offset'])
    except Exception:
        nextoffset = 0


    print "starting link_list"
    #link_list = RssArtistIndex.objects.raw("SELECT id, a.name, a.link, a.domain, a.date, a.title, count(*) as numArtist FROM rss_artist_index a where a.blacklist = 0 group by a.link order by a.date desc, a.name limit 20 offset %s", [nextoffset])
    link_list = RssArtistIndex.objects.raw("SELECT id, a.name, a.link, a.domain, a.date, a.title, count(*) as numArtist FROM rss_artist_index a where a.blacklist = 0 and date >= curdate() - INTERVAL DAYOFWEEK(curdate())+6 DAY group by a.link order by date desc limit 20 offset %s", [nextoffset])
    print "ending link_list"
    #predictions = []
    #for e in RssArtistIndex.objects.raw("SELECT id, a.name, a.link, b.content, a.domain, a.date, a.title, count(*) as numArtist FROM rss_artist_index a join rss_content b on a.link = b.link where a.blacklist = 0 group by a.link order by a.date desc, a.name limit 20 offset %s", [nextoffset]):
       #predictions.append(predict(e.content))
    #print predictions
    print "starting trending"
    trending = RssArtistIndex.objects.raw("SELECT id, a.name, count(*)-1 as total from rss_artist_index a join artist_cache b on a.name = b.name where type='Good' and date >= curdate() - INTERVAL DAYOFWEEK(curdate())+6 DAY group by a.name having count(*) > 1 order by count(*) desc limit 20")
    print "ending trending"
    print "starting date"
    date = RssArtistIndex.objects.raw("SELECT id, DATE(a.date) FROM rss_artist_index a group by DATE(a.date) order by a.date desc limit 1")
    print "ending date"
    '''
    cursor = connections['data'].cursor()
    print "starting row"
    cursor.execute("SELECT count(*) from (SELECT * FROM rss_artist_index  where blacklist = 0 group by link) temp")
    #cursor.execute("SELECT count(*) from (SELECT id, a.name, a.link, a.domain, a.date, a.title, count(*) as numArtist FROM rss_artist_index a where a.blacklist = 0 group by a.link order by a.date desc, a.name) temp")
    row = cursor.fetchone()
    cursor.close()
    '''
    row = {}
    row[0] = 1000
    print nextoffset
    print row[0]
    if nextoffset+20 >= row[0]:
        if nextoffset == 0:
            previousoffset = nextoffset
            nextoffset = nextoffset
        else:
            previousoffset = nextoffset - 20
            nextoffset = nextoffset
    else:
        if nextoffset == 0:
            previousoffset = 0
        else:
            previousoffset = nextoffset - 20
        nextoffset = nextoffset + 20
    print "ending row"
    context = {'link_list':link_list,
                #'predictions' : predictions,
                'trending':trending,
                'date' :date,
                'offset':nextoffset,
                'previousoffset':previousoffset,
        }
    return render(request, 'art/index.html', context)
def get_query_cols(string):
    m = re.findall( 'select(.*?)from', string, re.DOTALL)
    m = m[0].split(",")
    final = []
    for a in m:
        new = a.replace("distinct", "")
        new = new.strip()
        new = new.split(".")
        if len(new) > 1:
            new = new[1]
        else:
            new = new[0]
        new = new.title()
        test = new.lower().find(" as ")
        if test != -1:
            new = new[test+4:]
        final.append(new)
    return final

def top(request):
    if "id" in request.GET:
        lists = Toplists.objects.filter(id = int(request.GET['id']))
        query = lists[0].query
        conn = MySQLdb.connect(user='spjps2009', passwd='paintingisfun', db='mainDB', host='localhost', charset="utf8", use_unicode=True, cursorclass = cursors.Cursor)
        cur = conn.cursor()
        cur.execute("SET NET_WRITE_TIMEOUT = 28800")
        #cur.execute("select count(*) from rss_artist_index where name = %s", (name))
        cur.execute(query)
        results = cur.fetchall()
        cur.close()
        conn.close()
        columns = get_query_cols(query)
        output = []
        for result in results:
            new = {}
            for i in range(0,len(result)):
                temp = result[i]
                if isinstance(temp, basestring):
                    temp = temp.title()
                new[columns[i]] = temp
            output.append(new)
        data = json.dumps(output)
        return HttpResponse(data)

    tops = Toplists.objects.all()
    context = {
            'tops' : tops,
    }
    return render(request, 'art/top.html', context)



def stats(request):
    artist_total = ArtistScore.objects.raw("SELECT 0 as name,count(*) as total from artist_score")
    #artist_total = RssArtistIndex.objects.raw("SELECT id, count(distinct name) as total FROM rss_artist_index a where a.blacklist = 0")
    artist_rankings = ArtistScore.objects.raw("SELECT b.name as id, b.name, b.rank as artfacts_rank, a.score FROM artist_score a join artfacts b on a.name = b.name")
    #artist_rankings = {}
    start_date = (dt.date.today() - dt.timedelta(1*365/12)).strftime('%Y-%m-%d %H:%M:%S')
    feed_total = RssArtistIndex.objects.raw("SELECT 0 as id, count(*) as total FROM rss_artist_index a")
    live_feed = RssArtistIndex.objects.raw("SELECT id, date, domain, count(*) as total FROM rss_artist_index a where a.blacklist = 0 and date > %s group by DATE(date), domain having total < 500",[start_date] )

templates/art/changelog.html
{%extends 'art/base.html'%}
{% block content %}
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
<div id="page" class="row" style="font-family: 'Open Sans';">
    <div class="pi-section-w pi-section-white piGooglePrettify">
      <div class="pi-section">
          <h1 class="pi-margin-bottom-35">Docs - Changelog</h1>
          <h4 class="pi-uppercase pi-weight-700 pi-letter-spacing">Planned Features:</h4>
          <ul class="pi-list-with-icons pi-list-icons-dot pi-margin-bottom-30">
            <!--<li>Feature: Add current menu item highlighting feature to onepage versions.</li>-->
            <li>Artticker vs Artfacts Ranking Chart</li>
            <li>Add support for 2 level deep artist links</li>
            <li>Add support for other language galleries discovery</li>
            <li>Add submit gallery not working page</li>
             <!--<li>Update: Google captcha update.</li>
             <li>Fix: Portfolio items overlapping issue.</li>
             <li>Docs: captcha docs cahnged</li>-->
          </ul>

          <h4 class="pi-uppercase pi-weight-700 pi-letter-spacing">v1.0.1:<br><span class="pi-smaller-text">Jan 4, 2016</span></h4>
          <ul class="pi-list-with-icons pi-list-icons-dot pi-margin-bottom-30">
            <!--<li>Feature: Add current menu item highlighting feature to onepage versions.</li>-->
             <li>Update: Updated Art Facts to Latest: 1/4/2015</li>
             <!--<li>Update: Google captcha update.</li>
             <li>Fix: Portfolio items overlapping issue.</li>
             <li>Docs: captcha docs cahnged</li>-->
          </ul>
          <h4 class="pi-uppercase pi-weight-700 pi-letter-spacing">v1.0.0:<br><span class="pi-smaller-text">Jan 1, 2016</span></h4>
          <ul class="pi-list-with-icons pi-list-icons-dot pi-margin-bottom-30">
             <li>Update: Transferred to Rutgers VM</li>
          </ul>
       </div>
    </div>
 </div>
{% endblock %}

templates/art/clean.html
{%extends 'art/base.html'%}
{% block content %}
<div class="row">
	<div class="small-9 columns">
		{% load humanize %}
		{% load staticfiles %}
		{%for link in link_list%}
		<div class="panel callout radius">
			<div class="row" style="margin-bottom: 10px;">
				<div class="small-3 columns">
					<span class="right" style="font-size: 80%;">{{link.domain}}</span>
				</div>
			</div>
			<a href="{{link.link}}" target="_blank" id="url{{forloop.counter}}" onclick="displayData('{{artist.name}}', {{forloop.counter}})">
				{% if link.title and link.title %}
					{{link.title}}
				{%else%}
					{{link.link}}
				{%endif%}
			</a>
			<a href="#"><img src="{%static 'art/img/x.png'%}" onclick="removeLink('{{link.link}}');return false;" style="width:15px;height:15px;"></img></a>
			<br>
			<a href="#" id="more{{forloop.counter}}" onclick="showMore('{{link.link}}', {{forloop.counter}});return false" style="color:grey;">More</a>
			<p style="text-align: right; color:#999; ">{{link.date|naturaltime|capfirst}}</p>
		</div>
		{%endfor%}
		<div class="row">
			<a href="{%url 'art:index'%}?offset={{previousoffset}}" class="button">Previous</a>
			<a href="{%url 'art:index'%}?offset={{offset}}" class="button right">Next</a>
		</div>
	</div>
</div>
{% endblock %}

templates/art/file_upload.html
{%extends 'art/base.html'%}
{% block content %}
<script>
$(document).ready(function() {
    $("#submitArtistCsv").click(function(){
      $("#messageArtist").html('');
      $("#messageArtist").html($("#messageArtist").html() + '<div class="row"><div class="small-4 small-offset-4 columns"><a href="' + "{% url 'art:settings' %}" + '" class="success expanded button">Done</a></div></div>');
      {% for artist in artists %}
        $.ajax({
          url: '/art/add_artist/',
          type: 'get', //this is the default though, you don't actually need to always mention it
          data:{
              "artist": '{{artist}}',
              "gallery": {{gallery}},
            },
          success: function(data) {
              console.log(data);
              var message = ""
              if(data === '0'){
              message = "Successfully Added Artist: " + "{{artist}}";
                $("#messageArtist").html('<br><div class="success callout" data-closable><h6>' + message + '</h6><button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span></button></div>' + $("#messageArtist").html());
              }else if (data === '1'){
              message = "Artist " + "{{artist}}" + " Already Exists";
                $("#messageArtist").html('<br><div class="alert callout" data-closable><h6>' + message + '</h6><button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span></button></div>' + $("#messageArtist").html());
              }else{
                message = "Error Adding Artist";
                $("#messageArtist").html('<br><div class="alert callout" data-closable><h6>' + message + '</h6><button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span></button></div>' + $("#messageArtist").html());
              }
          },
          error: function(data) {
              message = "Error Adding Artist";
              $("#messageArtist").html('<div class="alert callout" data-closable><h6>' + message + '</h6><button class="close-button" aria-label="Dismiss alert" type="button" data-close><span aria-hidden="true">&times;</span></button></div>' + $("#messageArtist").html());
          }
        });
      {%endfor%}
    });
});
</script>
<div class="row">
  <div class="small-12 columns">
    {% load humanize %}
    {% load staticfiles %}
    {%if status == 0%}
      <div id="messageArtist">
        <div class="large-6 columns">
          <h3> Confirm Artist Upload</h3>
          <div class="success callout" data-closable>
            <h5> Artists: </h5>
            {%for artist in artists%}
              <div class="row">
                <div class="large-4 large-offset-2 columns">
                  &bull; {{artist}} 
                </div>
              </div>
            {%endfor%}
            <br>
            <h5>Gallery: </h5>
              <div class="row">
                <div class="large-4 large-offset-2 columns">
                  &bull; {{gallery_name}} 
                </div>
              </div>
          </div>
          <div class="row">
            <div class="small-4 small-offset-4 columns">
              <button id="submitArtistCsv" type="button" class="success expanded button">Save</button>
            </div>
          </div>
        </div>
      </div>
    {%endif%}
    {%if status == 1%}
      <div class="large-6 columns">
        <div class="alert callout" data-closable>
          <h4> Only One Column needed for Artist</h4>
        </div>
        <div class="row"><div class="small-4 small-offset-4 columns"><a href="{% url 'art:settings' %}" class="success expanded button">Done</a></div></div>
      </div>
    {%endif%}
    {%if status == 2%}
      <div class="large-6 columns">
        <div class="alert callout" data-closable>
          <h4> First column needs to be artists</h4>
        </div>
        <div class="row"><div class="small-4 small-offset-4 columns"><a href="{% url 'art:settings' %}" class="success expanded button">Done</a></div></div>
      </div>
    {%endif%}
    {%if status == 3%}
      <div class="large-6 columns">
        <div class="alert callout" data-closable>
          <h4> File Needs to Have more than 1 Row</h4>
        </div>
        <div class="row"><div class="small-4 small-offset-4 columns"><a href="{% url 'art:settings' %}" class="success expanded button">Done</a></div></div>
      </div>
    {%endif%}
    {%if status == 4%}
      <div class="large-6 columns">
        <div class="alert callout" data-closable>
          <h4> Headers and Rows Needs to Aligned Correctly</h4>
        </div>
        <div class="row"><div class="small-4 small-offset-4 columns"><a href="{% url 'art:settings' %}" class="success expanded button">Done</a></div></div>
      </div>
    {%endif%}
    {%if status == 5%}
      <div class="large-6 columns">
        <div class="alert callout" data-closable>
          <h4> Names need to have Minimum Two Words</h4>
        </div>
        <div class="row"><div class="small-4 small-offset-4 columns"><a href="{% url 'art:settings' %}" class="success expanded button">Done</a></div></div>
      </div>
    {%endif%}
  </div>
</div>
{% endblock %}

templates/art/gallery.html
{%extends 'art/base.html'%}
{% block content %}
<script>
function getNames(){
	if ($("#article").val() === ""){
		return
	}
	urls = $('textarea#article').val().split('\n');
	console.log(urls);
	$('#label').text("Getting Data");
	getUrls(0, urls)
}
function getUrls(curr_url, urls){
	console.log(curr_url)
	if(curr_url === urls.length){
		return
	}
	$.ajax({
		type: "POST",
		async: true,
		url: "../gallery_get/",
		data: { url:  urls[curr_url] },
		success: function(data){
			if (curr_url == 0){
				$('#label').text("");
			}
			$('#label').html($('#label').html() + urls[curr_url] + "<br>" + data + "<br><br>")
			console.log(data);
			new_index = curr_url + 1
			getUrls(new_index, urls)
		},
		error: function(data) {
			$('#label').html($('#label').html() + urls[curr_url] + "<br>" + "Error" + "<br><br>")
			console.log(data);
			new_index = curr_url + 1
			getUrls(new_index, urls)
		}
		});
}


</script>

<div class="row">
	<div class="small-12 columns">
		{% load humanize %}
		{% load staticfiles %}
		  <div class="row">
			 <div class="large-12 columns">
				 <div id="label1">
					<div id="label" data-alert class="alert-box success radius">
					  <a href="#" class="close">&times;</a>
					</div>
				 </div>
				<label>Test Gallery URL...
				  <textarea id="article" placeholder="URL..." rows="7"></textarea>
				</label>
				<br>
				<a href="#" class="button success" style="text-align:center" onclick="getNames()">Submit</a>
			 </div>
		  </div>


	</div>
</div>
{% endblock %}

templates/art/index.html
{%extends 'art/base.html'%}
{% block content %}
<div class="row">
	<div class="small-9 columns">
		{% load humanize %}
		{% load staticfiles %}
		{%for link in link_list%}
		<div class="panel callout radius">
			<div class="row" style="margin-bottom: 10px;">
				<div class="small-9 columns">
					<h5>
						<a href="javascript:void(0);" id="name{{forloop.counter}}" data-open="artistModal" onclick="displayData('{{link.name}}');">{{link.name}}</a>
					{%if link.numArtist|add:"-1" > 0%}
					<a href="#" id="show{{forloop.counter}}" onclick="getArtist('{{link.link}}', '{{link.name}}', {{forloop.counter}}, {{link.numArtist|add:"-1"}});return false;">
						<span class="round secondary label fi-plus lead"> {{link.numArtist|add:"-1"}} more</span>
					</a>
					{%endif%}
					</h5>
				</div>
				<div class="small-3 columns">
					<span class="right" style="font-size: 80%;">{{link.domain}}</span>
				</div>
			</div>
			<a href="{{link.link}}" target="_blank" id="url{{forloop.counter}}" onclick="displayData('{{artist.name}}', {{forloop.counter}})">
				{% if link.title and link.title %}
					{{link.title}}
				{%else%}
					{{link.link}}
				{%endif%}
			</a>
			<a href="#"><img src="{%static 'art/img/x.png'%}" onclick="removeLink('{{link.link}}');return false;" style="width:15px;height:15px;"></img></a>
			<br>
			<a href="#" id="more{{forloop.counter}}" onclick="showMore('{{link.link}}', {{forloop.counter}});return false" style="color:grey;">More</a>
			<p style="text-align: right; color:#999; ">{{link.date|naturaltime|capfirst}}</p>
		</div>
		{%endfor%}
		<div class="row">
			<a href="{%url 'art:index'%}?offset={{previousoffset}}" class="button">Previous</a>
			<a href="{%url 'art:index'%}?offset={{offset}}" class="button right">Next</a>
		</div>
	</div>
	<div class="small-3 columns">
		<h4 class="subheader text-center" style="color:#444">Trending</h4>
		<div class="row right panel" style="background-color:#f5f5f5">
			{%for trend in trending%}
			<h5 class="subheader" style="color:#666">
				<a href="javascript:void(0);" data-open="artistModal" onclick="displayData('{{trend.name}}');return false;">{{trend.name}}</a>
			</h5>
			{%endfor%}
		</div>
	</div>
</div>
{% endblock %}