art/urls.py
from django.conf.urls import url
from art import views
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import settings

urlpatterns = [#patterns(views',
        url(r'^$', views.index, name="index"),
        url(r'^trash/$', views.trash, name="trash"),
        url(r'^stats/$', views.stats, name="stats"),
        url(r'^top/$', views.top, name="top"),
        url(r'^gallery/$', views.gallery, name="gallery"),
        url(r'^location/$', views.location, name="location"),
        url(r'^get_score/$', views.get_score, name="get_score"),
        url(r'^demo/$', views.demo, name="demo"),
        url(r'^save_gallery/$', views.save_gallery, name="save_gallery"),
        url(r'^get_gallery_names/$', views.get_gallery_names, name="get_gallery_names"),
        url(r'^get_artist_status/$', views.get_artist_status, name="get_artist_status"),
        url(r'^get_galleries/$', views.get_galleries, name="get_galleries"),
        url(r'^gallery_get/$', views.gallery_get, name="gallery_get"),
        url(r'^svm/$', views.svm, name="svm"),
        url(r'^svm_add/$', views.svm_add, name="svm_add"),
        url(r'^svm_get_article/$', views.svm_get_article, name="svm_get_article"),
        url(r'^svm_add_article/$', views.svm_add_article, name="svm_add_article"),
        url(r'^svm_test/$', views.svm_test, name="svm_test"),
        url(r'^clean/$', views.clean, name="clean"),
        url(r'^removeLinkArtist/$', views.removeLinkArtist, name="removeLinkArtist"),
        url(r'^restoreLinkArtist/$', views.restoreLinkArtist, name="restoreLinkArtist"),
        url(r'^removeLink/$', views.removeLink, name="removeLink"),
        url(r'^restoreLink/$', views.restoreLink, name="restoreLink"),
        url(r'^getScore/$', views.getScore, name="getScore"),
        url(r'^getDomain/$', views.getDomain, name="getDomain"),
        url(r'^getArtistGallery/$', views.getArtistGallery, name="getArtistGallery"),
        url(r'^getLink/$', views.getLink, name="getLink"),
        url(r'^getTrash/$', views.getTrash, name="getTrash"),
        url(r'^getLatest/$', views.getLatest, name="getLatest"),
        url(r'^getMore/$', views.getMore, name="getMore"),
        url(r'^getArtist/$', views.getArtist, name="getArtist"),
        url(r'^settings/$', views.settings, name="settings"),
        url(r'^add_gallery/$', views.add_gallery, name="add_gallery"),
        url(r'^remove_gallery/$', views.remove_gallery, name="remove_gallery"),
        url(r'^add_artist/$', views.add_artist, name="add_artist"),
        url(r'^add_artist_test/$', views.add_artist_test, name="add_artist_test"),
        url(r'^remove_artist/$', views.remove_artist, name="remove_artist"),
        url(r'^remove_artist_all/$', views.remove_artist_all, name="remove_artist_all"),
        url(r'^remove_artfacts/$', views.remove_artfacts, name="remove_artfacts"),
        url(r'^upload_artist_csv/$', views.upload_artist_csv, name="upload_artist_csv"),
        url(r'^add_article/$', views.add_article, name="add_article"),
        url(r'^get_recent_articles/$', views.get_recent_articles, name="get_recent_articles"),
        url(r'^get_article/$', views.get_article, name="get_article"),
        url(r'^check_article/$', views.check_article, name="check_article"),
        url(r'^get_artist_from_website/$', views.get_artist_from_website, name="get_artist_from_website"),
        url(r'^add_mapping/$', views.add_mapping, name="add_mapping"),
        url(r'^remove_mapping/$', views.remove_mapping, name="remove_mapping"),
        url(r'^search_gallery/$', views.search_gallery, name="search_gallery"),
        url(r'^update_gallery/$', views.update_gallery, name="update_gallery"),
        url(r'^search_artist/$', views.search_artist, name="search_artist"),
        url(r'^search_artist_all/$', views.search_artist_all, name="search_artist_all"),
        url(r'^search_artfacts/$', views.search_artfacts, name="search_artfacts"),
        url(r'^changelog/$', views.changelog, name="changelog"),
        url(r'^search/', views.search, name="search" ),
]

#if settings.DEBUG == True:
        #urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('art.urls', namespace="art", app_name="art")),
    url(r'^art/', include('art.urls', namespace="art", app_name="art")),
    url(r'^music/', include('music.urls', namespace="music", app_name="music")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^art/', include('art.urls')),
]
if settings.DEBUG == True:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

music/urls.py
from django.conf.urls import url
from music import views

urlpatterns = [#patterns('music.views',
        url(r'^$', views.index, name="index"),
        url(r'^trash/$', views.trash, name="trash"),
        url(r'^stats/$', views.stats, name="stats"),
        url(r'^clean/$', views.clean, name="clean"),
        url(r'^removeLinkArtist/$', views.removeLinkArtist, name="removeLinkArtist"),
        url(r'^restoreLinkArtist/$', views.restoreLinkArtist, name="restoreLinkArtist"),
        url(r'^removeLink/$', views.removeLink, name="removeLink"),
        url(r'^restoreLink/$', views.restoreLink, name="restoreLink"),
        url(r'^getScore/(?P<name>[\w|\W]+)/$', views.getScore, name="getScore"),
        url(r'^getDomain/(?P<name>[\w|\W]+)/$', views.getDomain, name="getDomain"),
        url(r'^getLink/(?P<name>[\w|\W]+)/$', views.getLink, name="getLink"),
        url(r'^getTrash/(?P<name>[\w|\W]+)/$', views.getTrash, name="getTrash"),
        url(r'^getLatest/$', views.getLatest, name="getLatest"),
        url(r'^getMore/$', views.getMore, name="getMore"),
        url(r'^getArtist/$', views.getArtist, name="getArtist"),
        url(r'^search/$', views.search, name="search"),
]#)

music/models.py
from django.db import models

# Create your models here.

music/views.py
from django.shortcuts import render
from django.http import HttpResponse
from art.models import RssArtistIndex,RssContent
from django.core import serializers
from django.db import connections
import urllib2
import json
import datetime


# Create your views here.
def index(request):
    #template = loader.get_template('art/index.html')
    nextoffset = 0
    previousoffset = 0
    try:
        nextoffset = int(request.GET['offset'])
    except Exception as e:
        nextoffset = 0


    link_list = RssArtistIndex.objects.raw("SELECT id, a.name, a.link, a.domain, a.date, a.title, count(*) as numArtist FROM rss_artist_index_music a where a.blacklist = 0 group by a.link order by a.date desc, a.name limit 20 offset %s", [nextoffset])
    trending = RssArtistIndex.objects.raw("SELECT id, name, count(*)-1 as total from rss_artist_index_music where date >= (SELECT a.date FROM rss_artist_index_music a group by DATE(a.date) order by a.date desc limit 1) group by name having count(*) > 1 order by count(*) desc limit 20")
    date = RssArtistIndex.objects.raw("SELECT id, DATE(a.date) FROM rss_artist_index_music a group by DATE(a.date) order by a.date desc limit 1")
    cursor = connections['data'].cursor()
    cursor.execute("SELECT count(*) from (SELECT id, a.name, a.link, a.domain, a.date, a.title, count(*) as numArtist FROM rss_artist_index_music a where a.blacklist = 0 group by a.link order by a.date desc, a.name) temp")
    row = cursor.fetchone()
    print nextoffset
    print row[0]
    if nextoffset+20 >= row[0]:
        if nextoffset == 0:
            previousoffset = nextoffset
            nextoffset = nextoffset
        else:
            previousoffset = nextoffset - 20
            nextoffset = nextoffset
    else:
        if nextoffset == 0:
            previousoffset = 0
        else:
            previousoffset = nextoffset - 20
        nextoffset = nextoffset + 20
    context = {'link_list':link_list,
                'trending':trending,
                'date' :date,
                'offset':nextoffset,
                'previousoffset':previousoffset,
        }
    return render(request, 'music/index.html', context)

def stats(request):
    artist_total = RssArtistIndex.objects.raw("SELECT id, count(distinct name) as total FROM rss_artist_index_music a where a.blacklist = 0")
    artist_rankings = RssArtistIndex.objects.raw("SELECT id, name, artfacts_rank, count(*) as score FROM rss_artist_index_music a where a.blacklist = 0 group by a.name")
    artist_rankings2 = RssArtistIndex.objects.raw("SELECT id, artfacts_rank, count(*) as total FROM rss_artist_index_music a where a.blacklist = 0 and artfacts_rank > 1 group by artfacts_rank")
    start_date = (datetime.date.today() - datetime.timedelta(1*365/12)).strftime('%Y-%m-%d %H:%M:%S')
    feed_total = RssArtistIndex.objects.raw("SELECT id, count(distinct link) as total FROM rss_artist_index_music a where a.blacklist = 0")
    live_feed = RssArtistIndex.objects.raw("SELECT id, DATE(date) as date, domain, count(*) as total FROM rss_artist_index_music a where a.blacklist = 0 and date > %s group by DATE(date), domain having total < 500",[start_date] )
    artists_per_day = RssArtistIndex.objects.raw("SELECT id, DATE(date) as date, count(distinct name) as total FROM rss_artist_index_music a where a.blacklist = 0 and date > %s GROUP BY DATE(date) order by date desc",[start_date] )
    articles_per_day = RssArtistIndex.objects.raw("SELECT id, DATE(date) as date, count(distinct link) as total FROM rss_artist_index_music a where a.blacklist = 0 and date > %s GROUP BY DATE(date) order by date desc",[start_date] )
    article_percentage = RssContent.objects.raw("select link, a.domain, count(*) * 100 / (select count(*) from rss_content_music) as percent from rss_content_music a group by domain order by percent desc;");

    context = {
                'live_feed':live_feed,
                'feed_total':feed_total,
                'artist_total':artist_total,
                'artist_rankings':artist_rankings,
                'artist_rankings2':artist_rankings2,
                'artists_per_day' : artists_per_day,
                'articles_per_day': articles_per_day,
                'article_percentage': article_percentage,
                }
    return render(request, 'music/stats.html', context)

def clean(request):
    clean = RssContent.objects.raw("SELECT distinct a.link, a.domain, a.date, a.title, a.content from rss_content_music a join rss_artist_index_music b on a.link = b.link where name not in (select name from artfacts) order by date desc;")
    context = {
                'link_list' : clean
                }
    return render(request, 'music/clean.html', context)

def trash(request):
    artist_list = RssArtistIndex.objects.raw("SELECT id, a.link, a.domain, a.date, a.title FROM rss_artist_index_music a where a.blacklist = 1 order by a.date desc limit 150")
    context = {'link_list':artist_list,
                }
    return render(request, 'music/trash.html', context)

def getScore(request, name):
    artist_score = RssArtistIndex.objects.filter(name=name).count()
    return HttpResponse(artist_score)

def getDomain(request, name):
    artist_domain = RssArtistIndex.objects.filter(name=name).values('domain').distinct()
    data = json.dumps(list(artist_domain))
    return HttpResponse(data)

def getLink(request, name):
    artist_all = RssArtistIndex.objects.raw("SELECT id, a.link, a.domain, b.date, a.title FROM rss_artist_index_music a join rss_content_music b on a.link=b.link where name='" + name + "' and a.blacklist = 0 group by a.link order by b.date desc")
    data = serializers.serialize("json", artist_all)
    return HttpResponse(data)

def getTrash(request, name):
    artist_all = RssArtistIndex.objects.raw("SELECT id, a.link, a.domain, b.date, a.title FROM rss_artist_index_music a join rss_content_music b on a.link=b.link where name=%s and a.blacklist = 1 group by a.link order by b.date desc", [name])
    data = serializers.serialize("json", artist_all)
    return HttpResponse(data)

def getLatest(request):
    artist_all = RssArtistIndex.objects.raw("SELECT id, a.link, a.domain, b.date, a.title FROM rss_artist_index_music a join rss_content_music b on a.link=b.link where blacklist = 0 group by a.link order by b.date desc limit 300")
    data = serializers.serialize("json", artist_all)
    return HttpResponse(data)

def getArtist(request):
    url = request.GET['url']
    url = urllib2.unquote(url.decode("utf8"))
    name = urllib2.unquote(request.GET['name'].decode("utf-8"))
    artist_all = RssArtistIndex.objects.raw("SELECT id, name FROM rss_artist_index_music where link = %s and name <> %s order by name desc", [url, name])
    data = serializers.serialize("json", artist_all, fields=("name"))
    return HttpResponse(data)

def search(request):
    name = request.GET['q']
    artist_list = RssArtistIndex.objects.raw("SELECT id, a.name, max(date) as date FROM rss_artist_index_music a where name RLIKE %s group by name order by count(*) desc limit 30", ['[[:<:]]' + name + '[[:>:]]'])
    context = {'link_list':artist_list,}
        #print >>sys.stderr, p
    return render(request, 'music/search.html', context)

def removeLinkArtist(request):
    url = request.GET['url']
    name = urllib2.unquote(request.GET['name'].decode("utf-8"))
    url = urllib2.unquote(url.decode("utf8"))
    cursor = connections['data'].cursor()
    cursor.execute("UPDATE rss_artist_index_music set blacklist=1 where link = %s and name = %s", [url,name])
    return HttpResponse(url + " " + name)

def restoreLinkArtist(request):
    url = request.GET['url']
    name = urllib2.unquote(request.GET['name'].decode("utf-8"))
    url = urllib2.unquote(url.decode("utf8"))
    cursor = connections['data'].cursor()
    cursor.execute("UPDATE rss_artist_index_music set blacklist=0 where link = %s and name = %s", [url,name])
    return HttpResponse(url)

def removeLink(request):
    url = request.GET['url']
    url = urllib2.unquote(url.decode("utf8"))
    cursor = connections['data'].cursor()
    cursor.execute("UPDATE rss_artist_index_music set blacklist=1 where link = %s", [url])
    cursor.execute("UPDATE rss_content_music set blacklist=1 where link = %s", [url])
    return HttpResponse(url)

def restoreLink(request):
    url = request.GET['url']
    url = urllib2.unquote(url.decode("utf8"))
    cursor = connections['data'].cursor()
    cursor.execute("UPDATE rss_artist_index_music set blacklist=0 where link = %s", [url])
    cursor.execute("UPDATE rss_content_music set blacklist=0 where link = %s", [url])
    return HttpResponse(url)

def getMore(request):
    url = request.GET['url']
    url = urllib2.unquote(url.decode("utf8"))
    cursor = connections['data'].cursor()
    cursor.execute("Select * from rss_content_music where original_link = %s", [url])
    row = cursor.fetchone()
    artists = []
    cursor.execute("select artistName from artist_top10k")
    rows = cursor.fetchall()
    for r in rows:
        name = r[0].split(" ")
        if len(name) <= 1:
            continue
        if len(r[0]) < 4:
            continue
        if len(name[0]) <= 2 or len(name[1]) <= 2:
            continue
        if r[0] in row[6]:
            artists.append(r[0])

    artists_json = json.dumps(artists)
    return HttpResponse(artists_json)

templates/music/base.html
<html>
<head>
<title>Music</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/css/foundation.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/css/foundation.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/css/normalize.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css">
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/js/foundation.min.js"></script>
<script src="/static/art/js/art.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/canvasjs/1.4.1/canvas.min.js"></script>

<link href='http://fonts.googleapis.com/css?family=Roboto:300,200' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="row">
	<div class="large-7 columns">
		<h1>MusicTicker <small> Popularity of Musicians		 <div class="row right">
			 <div class="large-12 columns">
					<form method="get" action="{%url 'music:search' %}">
				<div class="row collapse">
				  <div class="small-9 columns">
					 <input type="text" placeholder="Search Artist" name="q" class="right">
				  </div>
				  <div class="small-3 columns">
					  <input type="submit" class="button postfix success" value="Go">
				  </div>
				</div>
			  </form>

			 </div>
		  </div>
		</div>
	</small></h1>

	<div class="large-5 columns">
		<div class="nav-bar right">
			<ul class="button-group">
				<li><a href="{%url 'music:index' %}" class="button success small">Music</a></li>
				<li><a href="{%url 'music:stats' %}" class="button success small">Statistics</a></li>
				<li><a href="{%url 'music:trash' %}" class="button success small">Trash</a></li>
				<li><a href="{%url 'art:index' %}" class="button small">Art</a></li>
				<li><a href="{%url 'music:index' %}" class="button small" style="background:#ffae00">Movies</a></li>
				<!--<li><a href="#" class="button">Link 3</a></li>-->
				<!--<li><a href="#" class="button">Link 4</a></li>-->
			</ul>
		</div>
	</div>
		<hr/>

</div>

{% block content %}

{% endblock %}
<div id="artistModal" class="reveal-modal" data-reveal>
	<h1 id="artistName" style="font-family: 'Roboto', sans-serif; font-weight: bold;"></h1>
	<h2 id="artistScore" style="font-family: 'Roboto', sans-serif;">Score:</h2>
	<h2 id="artistDomain" style="font-family: 'Roboto', sans-serif;">Domains:</h2>
	<h2 id="artistData" style="font-family: 'Roboto', sans-serif;">Data: </h2>
	<p id = "artistLink"style="font-family: 'Roboto', sans-serif;"></p>
	<h2 style="font-family: 'Roboto', sans-serif;">Trash: </h2>
	<p id = "artistTrash"style="font-family: 'Roboto', sans-serif;"></p>
	<a class="close-reveal-modal">&#215;</a>
</div>


<footer class="row">
	<div class="large-12 columns">
		<hr/>
		<div class="row">
			<div class="large-6 columns">
				<p>© Copyright.</p>
			</div>
			<div class="large-6 columns">
				<ul class="inline-list right">
					<li><a href="#">Link 1</a></li>
					<li><a href="#">Link 2</a></li>
					<li><a href="#">Link 3</a></li>
					<li><a href="#">Link 4</a></li>
				</ul>
			</div>
		</div>
	</div>
</footer>
</div>


</body>
</html>

templates/music/clean.html
{%extends 'music/base.html'%}
{% block content %}
<div class="row">
	<div class="small-9 columns">
		{% load humanize %}
		{% load staticfiles %}
		{%for link in link_list%}
		<div class="panel callout radius" style="background:#edfff2; border-color:#b7ffdc">
			<div class="row" style="margin-bottom: 10px;">
				<div class="small-3 columns">
					<span class="right" style="font-size: 80%;">{{link.domain}}</span>
				</div>
			</div>
			<a href="{{link.link}}" target="_blank" id="url{{forloop.counter}}" onclick="displayData('{{artist.name}}', {{forloop.counter}})">
				{% if link.title and link.title %}
					{{link.title}}
				{%else%}
					{{link.link}}
				{%endif%}
			</a>
			<a href="#"><img src="{%static 'art/img/x.png'%}" onclick="removeLink('{{link.link}}');return false;" style="width:15px;height:15px;"></img></a>
			<br>
			<a href="#" id="more{{forloop.counter}}" onclick="showMore('{{link.link}}', {{forloop.counter}});return false" style="color:grey;">More</a>
			<p style="text-align: right; color:#999; ">{{link.date|naturaltime|capfirst}}</p>
		</div>
		{%endfor%}
	</div>
</div>
{% endblock %}

templates/music/index.html
{%extends 'music/base.html'%}
{% block content %}
<div class="row">
	<div class="small-9 columns">
		{% load humanize %}
		{% load staticfiles %}
		{%for link in link_list%}
		<div class="panel callout radius" style="background:#edfff2; border-color:#b7ffdc">
			<div class="row" style="margin-bottom: 10px;">
				<div class="small-9 columns">
					<h5>
					<a href="#" id="name{{forloop.counter}}" data-reveal-id="artistModal" onclick="displayData('{{link.name}}')">{{link.name}}</a>
					{%if link.numArtist|add:"-1" > 0%}
					<a href="#" id="show{{forloop.counter}}" onclick="getArtist('{{link.link}}', '{{link.name}}', {{forloop.counter}}, {{link.numArtist|add:"-1"}});return false;">
						<span class="round secondary label fi-plus lead"> {{link.numArtist|add:"-1"}} more</span>
					</a>
					{%endif%}
					</h5>
				</div>
				<div class="small-3 columns">
					<span class="right" style="font-size: 80%;">{{link.domain}}</span>
				</div>
			</div>
			<a href="{{link.link}}" target="_blank" id="url{{forloop.counter}}" onclick="displayData('{{artist.name}}', {{forloop.counter}})">
				{% if link.title and link.title %}
					{{link.title}}
				{%else%}
					{{link.link}}
				{%endif%}
			</a>
			<a href="#"><img src="{%static 'art/img/x.png'%}" onclick="removeLink('{{link.link}}');return false;" style="width:15px;height:15px;"></img></a>
			<br>
			<a href="#" id="more{{forloop.counter}}" onclick="showMore('{{link.link}}', {{forloop.counter}});return false" style="color:grey;">More</a>
			<p style="text-align: right; color:#999; ">{{link.date|naturaltime|capfirst}}</p>
		</div>
		{%endfor%}
		<div class="row">
			<a href="{%url 'music:index'%}?offset={{previousoffset}}" class="button">Previous</a>
			<a href="{%url 'music:index'%}?offset={{offset}}" class="button right">Next</a>
		</div>
	</div>
	<div class="small-3 columns">
		<h4 class="subheader text-center" style="color:#444">Trending</h4>
		<div class="row right panel" style="background-color:#f5f5f5">
			{%for trend in trending%}
			<h5 class="subheader" style="color:#666">
				<a href="#" data-reveal-id="artistModal" onclick="displayData('{{trend.name}}')">{{trend.name}}</a>
			</h5>
			{%endfor%}
		</div>
	</div>
</div>
{% endblock %}

templates/music/index_bootstrap.html
<!--{% block content %}-->
<html>
<head>
<title>Art</title>
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>




<div class="panel-group" id="accordion">
	<div class="panel panel-default">
		{% for artist in artist_list %}
		 <div class="panel-heading" role="tab" id="heading{{forloop.counter}}">
			<h4 class="panel-title">
				<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#panel{{forloop.counter}}" aria-expanded="false" aria-controls="panel{{forloop.counter}}">
				 {{artist.name}}
			  </a>
			</h4>
		 </div>
		 <div id="panel{{forloop.counter}}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{forloop.counter}}">
			<div class="panel-body">
				hi
			</div>
		 </div>
		{%endfor%}
	</div>
</div>








<footer class="row">
	<div class="large-12 columns">
		<hr/>
		<div class="row">
			<div class="large-6 columns">
				<p>© Copyright.</p>
			</div>
			<div class="large-6 columns">
				<ul class="inline-list right">
					<li><a href="#">Link 1</a></li>
					<li><a href="#">Link 2</a></li>
					<li><a href="#">Link 3</a></li>
					<li><a href="#">Link 4</a></li>
				</ul>
			</div>
		</div>
	</div>
</footer>
</div>
</body>

</html>
<!--{% endblock %}-->

templates/music/search.html
{% extends 'music/base.html'%}
{% block content %}

<div class="row">
	<div class="small-9 columns">
		{% load humanize %}
		{%for link in link_list%}
			<div class="panel callout radius">
				<h5><a href="#" data-reveal-id="artistModal" onclick="displayData('{{link.name}}')">{{link.name}}</a></h5>
				<p style="text-align: right; color:#999; ">Last seen: {{link.date|naturalday|capfirst}}</p>
			</div>

		{%endfor%}
	</div>
</div>



{% endblock %}

templates/music/trash.html
{% extends 'music/base.html'%}
{% block content %}

<div class="row">
	<div class="small-12 columns">
		{% load humanize %}
		{% load staticfiles %}
		{%for link in link_list%}
			<div class="panel callout radius">
				<h5><a href="#" data-reveal-id="artistModal" onclick="displayData('{{link.name}}')">{{link.name}}</a><small class="right">{{link.domain}}</small></h5>
				<a href="{{link.link}}" id="url{{forloop.counter}}" onclick="displayData('{{artist.name}}', {{forloop.counter}})">
					{{link.title}}
				</a>
				<a href="#"><img src="{%static 'art/img/x.png'%}" onclick="restoreLink('{{link.link}}');return false;" style="width:15px;height:15px;"></img></a>
				<p style="text-align: right; color:#999; ">{{link.date|naturaltime|capfirst}}</p>
			</div>

		{%endfor%}
	</div>
</div>



{% endblock %}